import type { Task } from "../types";
import { dateFromToday } from "../../../lib/date";

export const initialTasks: Task[] = [
  {
    id: 1,
    title: "完成前端首页布局",
    description: "设计并实现 AI TODO 系统的 Dashboard 首页。",
    status: "进行中",
    priority: "高",
    category: "前端开发",
    dueDate: dateFromToday(2),
    dueTime: "15:00",
    createdAt: dateFromToday(-2),
    completedAt: null,
    tags: ["React", "UI设计"],
    aiReason: "该任务是后续功能开发的基础，建议优先完成。",
    estimatedTime: "2小时",
    aiCategory: "核心开发",
    isAiCreated: false,
  },
  {
    id: 2,
    title: "整理接口文档",
    description: "根据后端接口整理前端调用说明。",
    status: "待办",
    priority: "中",
    category: "文档",
    dueDate: dateFromToday(3),
    dueTime: "10:00",
    createdAt: dateFromToday(-2),
    completedAt: null,
    tags: ["API", "协作"],
    aiReason: "接口文档会影响前后端联调效率。",
    estimatedTime: "1小时",
    aiCategory: "协作文档",
    isAiCreated: false,
  },
  {
    id: 3,
    title: "测试任务分类功能",
    description: "验证 AI 自动分类和手动标签编辑是否一致。",
    status: "待办",
    priority: "高",
    category: "测试",
    dueDate: dateFromToday(1),
    dueTime: "16:00",
    createdAt: dateFromToday(-1),
    completedAt: null,
    tags: ["AI", "测试"],
    aiReason: "截止时间最近，并且会阻塞演示验收。",
    estimatedTime: "1.5小时",
    aiCategory: "质量保障",
    isAiCreated: true,
    confidence: 0.86,
    rawDueText: "明天下午",
  },
  {
    id: 4,
    title: "设计任务详情抽屉",
    description: "展示任务字段、子任务和 AI 分析结果。",
    status: "进行中",
    priority: "中",
    category: "前端开发",
    dueDate: dateFromToday(4),
    dueTime: "14:00",
    createdAt: dateFromToday(-1),
    completedAt: null,
    tags: ["Drawer", "交互"],
    aiReason: "详情抽屉能提升任务编辑效率。",
    estimatedTime: "2小时",
    aiCategory: "体验优化",
    isAiCreated: false,
  },
  {
    id: 5,
    title: "修复统计页空数据状态",
    description: "没有任务时图表区域需要显示合理的空态。",
    status: "待办",
    priority: "中",
    category: "数据统计",
    dueDate: dateFromToday(5),
    dueTime: "11:00",
    createdAt: dateFromToday(-1),
    completedAt: null,
    tags: ["统计", "空态"],
    aiReason: "统计页会用于展示项目完整性。",
    estimatedTime: "1小时",
    aiCategory: "数据体验",
    isAiCreated: false,
  },
  {
    id: 6,
    title: "准备课程项目演示脚本",
    description: "梳理从登录、任务创建、AI 推荐到统计分析的演示路线。",
    status: "待办",
    priority: "高",
    category: "演示",
    dueDate: dateFromToday(2),
    dueTime: "18:00",
    createdAt: dateFromToday(0),
    completedAt: null,
    tags: ["答辩", "演示"],
    aiReason: "演示脚本直接影响答辩表达质量。",
    estimatedTime: "1.5小时",
    aiCategory: "项目交付",
    isAiCreated: true,
    confidence: 0.91,
    rawDueText: "这周",
  },
  {
    id: 7,
    title: "接入 BYOK 设置页",
    description: "实现 OpenAI API Key 保存、测试和脱敏展示。",
    status: "待办",
    priority: "中",
    category: "后端联调",
    dueDate: dateFromToday(6),
    dueTime: "17:00",
    createdAt: dateFromToday(0),
    completedAt: null,
    tags: ["BYOK", "设置"],
    aiReason: "AI 能力依赖 BYOK 配置，建议在核心 UI 后联调。",
    estimatedTime: "2小时",
    aiCategory: "AI 能力",
    isAiCreated: false,
  },
  {
    id: 8,
    title: "完成移动端 Web 适配",
    description: "Sidebar 改为底部导航，任务卡片纵向排列。",
    status: "待办",
    priority: "低",
    category: "响应式",
    dueDate: dateFromToday(7),
    dueTime: "13:00",
    createdAt: dateFromToday(0),
    completedAt: null,
    tags: ["移动端", "WebView"],
    aiReason: "App 套壳前需要保证移动 Web 可用。",
    estimatedTime: "3小时",
    aiCategory: "跨端体验",
    isAiCreated: false,
  },
  {
    id: 9,
    title: "补充任务表格分页逻辑",
    description: "支持搜索、筛选、排序和分页联动。",
    status: "已完成",
    priority: "中",
    category: "前端开发",
    dueDate: dateFromToday(0),
    dueTime: "09:00",
    createdAt: dateFromToday(-2),
    completedAt: dateFromToday(0),
    tags: ["表格", "筛选"],
    aiReason: "任务表格是全部任务页的主要交互。",
    estimatedTime: "1小时",
    aiCategory: "核心开发",
    isAiCreated: false,
  },
  {
    id: 10,
    title: "整理后续灵感池",
    description: "记录暂时没有明确截止时间的产品想法和优化点。",
    status: "待办",
    priority: "低",
    category: "产品规划",
    dueDate: "",
    dueTime: "",
    createdAt: dateFromToday(0),
    completedAt: null,
    tags: ["灵感", "待排期"],
    aiReason: "没有明确截止时间，适合作为低压任务池持续维护。",
    estimatedTime: "30分钟",
    aiCategory: "任务整理",
    isAiCreated: false,
  },
];
